import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {useEffect, useState} from "react";

export default function Home() {
  const [parsedYaml, setParsedYaml] = useState([])

    useEffect(() => {
        const fetchMethod = (filePath: string) => {
            return fetch(`/api/generate?filePath=${filePath}`, {
                method: "GET",
            })
                .then((data) => data.json())
                .then((json) => json);
        };

        fetchMethod("https://storage.yandexcloud.net/api-bucket/api_1_3_39.json")
            .then((data) => {
                console.log(data);
                setParsedYaml(data);
            });
    }, []);
  return (
    <>
      <Head>
        <title>Автотест 4000</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          Общее количество эндпоинтов: {parsedYaml.length}
        </div>
      </main>
    </>
  )
}
